### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by vincequeiroz** [juriansluiman/SlmMail#103]
The last version of ZendMail requires the php version greater than 5.5 and less than 7.0.
The version 2.5.0 require PHP greater than 5.3.23.

The problem is a that as of PHP 5.4 you can also use the short array syntax, which replaces array() with []. That change broke the test with PHP 5.3.

In HeaderValue validation is used short array syntax.

https://github.com/zendframework/zend-mail/blob/master/src/Header/HeaderValue.php#L90
https://github.com/zendframework/zend-mail/blob/release-2.7.1/composer.json#L16
https://github.com/zendframework/zend-mail/blob/release-2.5.0/composer.json#L16
https://github.com/juriansluiman/SlmMail/blob/master/composer.json#L33

**Comment by bakura10** [comment]
Fixed in 2.0.0.
