### ISSUE TITLE
Mailgun as email transporter

### ISSUE THREAD

**Issue by kimek** [juriansluiman/SlmMail#108]
Hi Guys
Am I missing something or there is no option to use mailgun only as transporter ?

**Comment by bakura10** [comment]
Hi,

The documentation explain how you can get the transporter: https://github.com/juriansluiman/SlmMail/blob/master/docs/Mailgun.md#use-service-locator

**Comment by kimek** [comment]
Cheers @bakura10 .
I mean set transport as 'global'. I'm working on quiet messy zend sites where are dozen of classes which using Zend\Mail\** in vary different way. There are a lot of wrappers on top of it. That's why I'm looking for solution to set it as 'global' something like:
`class Mailgun_Mail_Transport_Mailgun extends Zend_Mail_Transport_Abstract`

**Comment by bakura10** [comment]
Hmm you're going outside the scope of what I know here :p... If you have a service locator (but if it's messy, I suppose you don't have :p) you could overrdie the default key, so whenever they ask a given transport, you modify the factory to return a MailGun transport. But if the code is ugly and without proper injection, I'm afraid that you'll need to suffer a bit =).

**Comment by kimek** [comment]
True, I don't have locator service :). This bits I miss in this code. In this case I will 'play carmagedon' with this code. Thanks for help @bakura10 . All the best !
