### ISSUE TITLE
SSLv3 failure at Mandrill

### ISSUE THREAD

**Issue by dzenkovich** [juriansluiman/SlmMail#89]
Using SLMMail for Mandrill integration.

I'm getting the SSLv3 error, every time I'm trying to use Mandrill service:
```
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

I did try to write the list of ciphers into /mods_available/ssl.conf but seems like this has no effect
I've also found this blog article http://blog.mandrill.com/poodle-sslv3-update.html that states SSLv3 was disabled by Mandrill.
So given I've tried removing it from ssl.conf I have no idea why it keeps using it at SLMMail.
P.S. trying `curl -v https://mandrillapp.com` results with an OK connection using `SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384`

**Comment by dzenkovich** [comment]
Fixed the problem by being able to update `Zend\Http\Client` connection adapter settings to `'ssltransport' => 'tls'`in them main Slm config file like:

```
'slm_mail' => array(

        'http_options' => array(
            'ssltransport' => 'tls',
            'sslverifypeer' => false,
            'persistent' => true,
        ),

     ...
```

**Comment by juriansluiman** [comment]
`'sslverifypeer' => false` is an extreme wrong solution to the problem. It simply says that you try to use TLS but you don't actually check the cert. In other words, anyone with a fake cert can trick you into using their service.

You better check out other options (e.g. sslcapath) to fix the issue because now you're having a massive security leak.

**Comment by dzenkovich** [comment]
Yes I'm aware of that option and it is not related to this specific problem. Thanks for sharing your thoughts, though.

**Comment by juriansluiman** [comment]
Oops @dzenkovich I opened this issue again :p. Was not meant to be. Just if you're aware, I've done my duty ;)
